name: 🔂 Unit tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    paths:
      - "src/**"
      - "tests/**"
      - "Cargo.toml"
      - ".github/workflows/test.yml"

jobs:
  unit-tests:
    name: cargo test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: "Install Rust toolchain"
        run: rustup show

      - uses: Swatinem/rust-cache@v2

      - name: "Run tests"
        shell: bash
        run: cargo test

  cargo-fmt:
    name: cargo fmt
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: "Install Rust toolchain"
        run: rustup component add rustfmt

      - run: cargo fmt --all --check

  cargo-clippy:
    name: cargo clippy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: "Install Rust toolchain"
        run: |
          rustup component add clippy
          rustup target add wasm32-unknown-unknown

      - uses: Swatinem/rust-cache@v2

      - name: "Clippy"
        run: cargo clippy --workspace --all-targets --all-features
